### ISSUE TITLE
kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by garywoodfine** [cake-build/cake-rider#118]
Plugin version: ```0.3.1```
IDE version: ```RD-211.6693.105```
Exception: ```kotlin.KotlinNullPointerException```
Stacktrace:
```text
kotlin.KotlinNullPointerException
	at net.cakebuild.actions.CakeTasksTreeAction.getWindow(CakeTasksTreeAction.kt:11)
	at net.cakebuild.actions.CakeTasksTreeAction$ExpandAll.actionPerformed(CakeTasksTreeAction.kt:23)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:616)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:676)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:675)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:626)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:486)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:481)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:232)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:889)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:833)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I updated the plugin version this morning, but I have also updated to the latest Rider release 2021.1  so might be connected

**Comment by nils-a** [comment]
@garywoodfine Thanks for reporting the issue.

I assume you're still on linux? (Seems the new reporting component lacks that information currently.)

**Comment by garywoodfine** [comment]
Yes I am on Linux. I should've added that in.

**Comment by nils-a** [comment]
No problem - I should have added that on the reporting component.

I am, however, unable to reproduce the error on windows or linux (Ubuntu 20.04) in Rider 2021.1
Did you do something "special"? From the looks of it, you triggered "Expand all" in the Cake Tasks window. Anything special in the project setup?

**Comment by garywoodfine** [comment]
No nothing special.  I have a very simple project at this stage.  Feel free to check it out thttps://github.com/garywoodfine/Blog-Tutorials

I just pulled the 0.3.1 release of the plugin this evening seems to have fixed it. I'll keep an eye on it and let you know.
