### ISSUE TITLE
java.lang.NoClassDefFoundError: com/intellij/codeInsight/hints/InlayPresentationFactory$DefaultImpls

### ISSUE THREAD

**Issue by olsh** [cake-build/cake-rider#301]
I get the following error when opening the cake file in my project
https://github.com/olsh/dotnet-consolidate/blob/master/build.cake

Plugin version: `4.0.0`
IDE version: `2022.3 (RD-223.7571.232)`
Operating system: `Windows 10`
Exception: `java.lang.NoClassDefFoundError: com/intellij/codeInsight/hints/InlayPresentationFactory$DefaultImpls`
Stacktrace:
```text
java.lang.NoClassDefFoundError: com/intellij/codeInsight/hints/InlayPresentationFactory$DefaultImpls
	at net.cakebuild.language.codeInsight.TaskInlayHintsProvider$TaskInlayHintsCollector.collect(TaskInlayHintsProvider.kt:78)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:92)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation$lambda-0(InlayHintsPass.kt:47)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$2(JobLauncherImpl.java:137)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$3(JobLauncherImpl.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:847)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:144)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:44)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation(InlayHintsPass.kt:38)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:397)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:396)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:372)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:370)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: com.intellij.codeInsight.hints.InlayPresentationFactory$DefaultImpls PluginClassLoader(plugin=PluginDescriptor(name=Cake for Rider, id=net.cakebuild.cakerider, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\223.7571.232.plugins\cake-rider, version=4.0.0, package=null, isBundled=false), packagePrefix=null, instanceId=74, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 34 more

```

**Comment by nils-a** [comment]
@olsh Sorry to hear you're having problems. Does this occur in a special constellation?

**Comment by olsh** [comment]
The issue trigerrs every time when I open the solution and open the cake file in the solution explorer.
Then I get the error and infinite `Analyzing...` status in the top right corner.

![image](https://user-images.githubusercontent.com/3613592/206926140-6827cf75-37f3-4f77-9a4f-558e982cb5a2.png)

**Comment by nils-a** [comment]
This is currently blocked by https://youtrack.jetbrains.com/issue/RIDER-86051

**Comment by nils-a** [comment]
@olsh, @garywoodfine, @simendsjo 
I have created a preview package [in the `beta` channel](https://plugins.jetbrains.com/plugin/15729-cake-for-rider/versions/beta). It will be available there for manual download and install, once JetBrains is done reviewing the package.
