### ISSUE TITLE
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'net.cakebuild.actions.CakeTasksTreeAction$TaskOnlyActions$Execute' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: net.cakebuild.cakerider]

### ISSUE THREAD

**Issue by nils-a** [cake-build/cake-rider#422]
Plugin version: `8.0.1`
IDE version: `2024.1 EAP 9 (RD-241.14494.107)`
Operating system: `Windows 11`
Exception: `com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'net.cakebuild.actions.CakeTasksTreeAction$TaskOnlyActions$Execute' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: net.cakebuild.cakerider]`
Stacktrace:
```text
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'net.cakebuild.actions.CakeTasksTreeAction$TaskOnlyActions$Execute' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: net.cakebuild.cakerider]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

```

**Comment by nils-a** [comment]
Probably related to #420
