### ISSUE TITLE
0.2.0 Plugin startup exception

### ISSUE THREAD

**Issue by Eragra3** [cake-build/cake-rider#73]
Hello guys,

after recent update I got an exception when starting Rider.
Not sure if exception itself will tell you anything, but looks like Cake plugin is failing when there are no cake scripts in project.

This is my guess, my project does **not** have any cake files.
I don't have any task in Cake Tasks window.

**Edit:** My project doesn't actually have any cake files.

```
kotlin.KotlinNullPointerException
	at net.cakebuild.actions.CakeTasksTreeAction.getWindow(CakeTasksTreeAction.kt:11)
	at net.cakebuild.actions.CakeTasksTreeAction$TaskOnlyActions.update(CakeTasksTreeAction.kt:39)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:178)
	at com.intellij.ide.util.gotoByName.GotoActionModel.updateActionBeforeShow(GotoActionModel.java:337)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.lambda$getPresentation$0(GotoActionModel.java:701)
	at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$updateOnEdt$4(GotoActionModel.java:495)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by nils-a** [comment]
Thanks for the report. This actually looks a bit like #68 
What operating system are you on?

**Comment by Eragra3** [comment]
Sorry I didn't check for duplicates.

I'm on Windows 10, Rider 2020.3.2

**Comment by nils-a** [comment]
No problem. I never had that on windows. 
Do you always have that error on start?

Would you be willing to test a bleeding-edge-version? 
You could download the CI build from #70 which is at https://github.com/cake-build/cake-rider/suites/1859799359/artifacts/36141996 and install that plugin manually.
That version has #68 fixed.

**Comment by augustoproiete** [comment]
I was unable to reproduce on Windows 10 and Rider 2020.3.2. I tried the following so far:

- Create Console app (.NET Core)
- Create Console app (.NET Framework)
- Create WPF app (.NET Core)
- Create WPF app (.NET Framework)
- Create empty solution
- Opened / Closed Rider multiple times
- Opened / Closed the projects above several times
- Opened / Closed the Cake Tasks sidebar multiple times (always empty as expected)

**Comment by Eragra3** [comment]
Hello again, I've used this plugin for about a week after I created this issue and also couldn't reproduce.

Sorry for confusion, but it seems like the issue is gone and thread can't be closed.
