### ISSUE TITLE
Cake Tasks window not working on linux

### ISSUE THREAD

**Issue by garywoodfine** [cake-build/cake-rider#99]
### Overview

Cake for rider : 0.2.0
OS: Ubuntu 20.04 & POPOS 20.10
Rider : 2020.3.4 

After installing Cake for Rider the cake tasks in the Cake Tool Window are not loaded.

Logs: 

``` bash
Cannot init toolwindow net.cakebuild.toolwindow.CakeTasksWindowFactory@4848054e

java.lang.NullPointerException
	at net.cakebuild.toolwindow.CakeTasksWindow$MyTreeCellRenderer.getTreeCellRendererComponent(CakeTasksWindow.kt:167)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRenderer(DefaultTreeUI.java:166)
	at com.intellij.ui.tree.ui.DefaultTreeUI$1.getNodeDimensions(DefaultTreeUI.java:380)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:493)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.updateNodeSizes(VariableHeightLayoutCache.java:903)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.invalidateSizes(VariableHeightLayoutCache.java:371)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.setCellRenderer(BasicTreeUI.java:465)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.propertyChange(BasicTreeUI.java:3816)
	at com.intellij.ui.tree.ui.DefaultTreeUI$4.propertyChange(DefaultTreeUI.java:487)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8754)
	at java.desktop/javax.swing.JTree.setCellRenderer(JTree.java:775)
	at net.cakebuild.toolwindow.CakeTasksWindow.<init>(CakeTasksWindow.kt:33)
	at net.cakebuild.toolwindow.CakeTasksWindowFactory.createToolWindowContent(CakeTasksWindowFactory.kt:12)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:506)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:486)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:980)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:926)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:915)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doRegisterToolWindow(ToolWindowManagerImpl.kt:1054)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.initToolWindows(ToolWindowManagerImpl.kt:486)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.access$initToolWindows(ToolWindowManagerImpl.kt:90)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$beforeProjectOpened$2.run(ToolWindowManagerImpl.kt:423)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

screenshot:
![image](https://user-images.githubusercontent.com/25871588/111903428-2ea16f00-8a3a-11eb-9077-75bee87d3493.png)

**Comment by nils-a** [comment]
This resembles an exception I had once in #68 but could never reproduce.

Are you able to reproduce it?

**Comment by garywoodfine** [comment]
@nils-a  it appears to be exactly the same error.
![image](https://user-images.githubusercontent.com/25871588/112765619-deac4480-9005-11eb-9fc7-85587432267e.png)

I have tried uninstalling and re-installing the plugin, but I get the same result.   I have tried on both Ubuntu and Pop OS with the same result.  I haven't tried on a Fedora machine yet.  

I suspect however that this is more of a Jetbrains API issue.

**Comment by nils-a** [comment]
@garywoodfine thanks for confirming. Interestingly enough - now I am able to reproduce the error, too. (Using Ubuntu 20.04, Rider 2020.3.4 and Cake for Rider 0.2.0)

Would you be willing to test an unstable develop build? 

I manually installed [0.3.0-pull-103-merge0001](https://github.com/cake-build/cake-rider/suites/2360036548/artifacts/49970806) which is the artifact from the [latest PR run](https://github.com/cake-build/cake-rider/actions/runs/693668322). This build seems to fix the issue.

**Comment by garywoodfine** [comment]
@nils-a  Sure I can certainly test an unstable build. If it helps.

**Comment by nils-a** [comment]
@garywoodfine thanks for doing that.

Cake for Rider defaults to using the globally installed cake tool (`dotnet tool install cake.tool -g`), alternatively you could point the plugin to the location of your installed cake tool using the settings:
![image](https://user-images.githubusercontent.com/349188/112833751-7443e480-9097-11eb-899b-942ba9ae3d18.png)

**Comment by garywoodfine** [comment]
@nils-a  thanks so much for that tip.

I figured it out from your illustration what I had to do in the end was as below.

![image](https://user-images.githubusercontent.com/25871588/112837218-83289800-9093-11eb-9316-202c14b402eb.png)


The Cake Tasks window now works great!  Really pleased with it!
Thanks for taking the time fix this!

P.S I have made a small contribution to Cake on Open Collective. really appreciate the effort you maintainers put into the projects

**Comment by nils-a** [comment]
You're very welcome.

I'll still have a look at the exec-statement. I am a bit surprised that `/home/woody/.dotnet/tools/dotnet-cake` would work for you while  `~/.dotnet/tools/dotnet-cake` would not.

> I have made a small contribution to Cake on Open Collective. really appreciate the effort you maintainers put into the projects

Thanks for doing that! It's really appreciated!

**Comment by nils-a** [comment]
@garywoodfine I am tracking the issue with the runner setting of `~/.dotnet/tools/dotnet-cake` not working as expected in ubuntu in #104 

As it seems the problem of this issue is resolved in the current codebase I'll move to closing this, if that's ok with you.

**Comment by nils-a** [comment]
@garywoodfine I [released](https://github.com/cake-build/Cake-Rider/releases/tag/0.3.0) [version 0.3.0](https://plugins.jetbrains.com/plugin/15729-cake-rider/versions/) today, which contains the fix for this problem(s).

**Comment by garywoodfine** [comment]
Already downloaded it earlier😊 , works perfect thanks. Really appreciate it
